#include "ast.h"
#include "grain_resolve.h"
#include "interpreter.h"
#include "signal_state.h"
#include "lexer.h"
#include "parser.h"
#include "vm/compiler.h"
#include "vm/vm.h"
#include "vm/debug.h"
#include <algorithm>
#include <csignal>
#include <cstdlib>
#include <cstring>
#include <fcntl.h>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <optional>
#include <sstream>
#include <vector>
#include <sys/wait.h>
#include <unistd.h>
#ifdef HAVE_READLINE
#include <readline/readline.h>
#include <readline/history.h>
#endif

// ── Version ──────────────────────────────────────────────────
//
// `version.h` is generated by the Makefile from `git describe --tags`,
// falling back to the VERSION file when building from a tarball with
// no .git directory. Don't edit by hand — update VERSION (or push a
// tag) and rebuild.
#include "version.h"

// ── Exit codes ───────────────────────────────────────────────
// Documented in --help. `sys.exit(N)` from user code passes through
// unchanged via ExitSignal, so any value other than these is a user
// choice — don't repurpose 0–3.
namespace ExitCode {
    constexpr int Success      = 0;
    constexpr int UsageError   = 1; // bad CLI args, file not found, no test files
    constexpr int CompileError = 2; // lex / parse / bytecode codegen failure
    constexpr int RuntimeError = 3; // uncaught exception, VM/interpreter failed
}

// ── AST printer ──────────────────────────────────────────────

static void printIndent(int level) {
    for (int i = 0; i < level; i++) std::cout << "  ";
}

static void printExpr(const Expr* expr, int level);
static void printStmt(const Stmt* stmt, int level);

static void printExpr(const Expr* expr, int level) {
    if (!expr) { printIndent(level); std::cout << "<null>\n"; return; }

    switch (expr->type) {
    case ExprType::Number: {
        auto* e = static_cast<const NumberExpr*>(expr);
        printIndent(level);
        if (e->isInt) std::cout << "Int(" << e->intValue << ")\n";
        else std::cout << "Float(" << e->floatValue << ")\n";
        break;
    }
    case ExprType::String: {
        auto* e = static_cast<const StringExpr*>(expr);
        printIndent(level); std::cout << "String(\"" << e->value << "\")\n";
        break;
    }
    case ExprType::Bool: {
        auto* e = static_cast<const BoolExpr*>(expr);
        printIndent(level); std::cout << "Bool(" << (e->value ? "true" : "false") << ")\n";
        break;
    }
    case ExprType::Nil:
        printIndent(level); std::cout << "Nil\n";
        break;
    case ExprType::Identifier: {
        auto* e = static_cast<const IdentifierExpr*>(expr);
        printIndent(level); std::cout << "Ident(" << e->name << ")\n";
        break;
    }
    case ExprType::Unary: {
        auto* e = static_cast<const UnaryExpr*>(expr);
        printIndent(level); std::cout << "Unary(" << tokenTypeToString(e->op) << ")\n";
        printExpr(e->operand.get(), level + 1);
        break;
    }
    case ExprType::Binary: {
        auto* e = static_cast<const BinaryExpr*>(expr);
        printIndent(level); std::cout << "Binary(" << tokenTypeToString(e->op) << ")\n";
        printExpr(e->left.get(), level + 1);
        printExpr(e->right.get(), level + 1);
        break;
    }
    case ExprType::Postfix: {
        auto* e = static_cast<const PostfixExpr*>(expr);
        printIndent(level); std::cout << "Postfix(" << tokenTypeToString(e->op) << ")\n";
        printExpr(e->operand.get(), level + 1);
        break;
    }
    case ExprType::Assign: {
        auto* e = static_cast<const AssignExpr*>(expr);
        printIndent(level); std::cout << "Assign(" << e->name << ")\n";
        printExpr(e->value.get(), level + 1);
        break;
    }
    case ExprType::Call: {
        auto* e = static_cast<const CallExpr*>(expr);
        printIndent(level); std::cout << "Call\n";
        printExpr(e->callee.get(), level + 1);
        for (const auto& arg : e->args)
            printExpr(arg.get(), level + 1);
        break;
    }
    case ExprType::Ternary: {
        auto* e = static_cast<const TernaryExpr*>(expr);
        printIndent(level); std::cout << "Ternary\n";
        printExpr(e->condition.get(), level + 1);
        printExpr(e->thenExpr.get(), level + 1);
        printExpr(e->elseExpr.get(), level + 1);
        break;
    }
    case ExprType::Pipe: {
        auto* e = static_cast<const PipeExpr*>(expr);
        printIndent(level); std::cout << "Pipe\n";
        printExpr(e->left.get(), level + 1);
        printExpr(e->right.get(), level + 1);
        break;
    }
    case ExprType::Async: {
        auto* e = static_cast<const AsyncExpr*>(expr);
        printIndent(level); std::cout << "Async\n";
        printExpr(e->expr.get(), level + 1);
        break;
    }
    case ExprType::Await: {
        auto* e = static_cast<const AwaitExpr*>(expr);
        printIndent(level); std::cout << "Await\n";
        printExpr(e->expr.get(), level + 1);
        break;
    }
    case ExprType::This:
        printIndent(level); std::cout << "This\n";
        break;
    case ExprType::Super: {
        auto* e = static_cast<const SuperExpr*>(expr);
        printIndent(level); std::cout << "Super." << e->method << "\n";
        break;
    }
    case ExprType::InterpolatedString: {
        auto* e = static_cast<const InterpolatedStringExpr*>(expr);
        printIndent(level); std::cout << "InterpString\n";
        for (const auto& part : e->parts)
            printExpr(part.get(), level + 1);
        break;
    }
    case ExprType::Lambda: {
        auto* e = static_cast<const LambdaExpr*>(expr);
        printIndent(level); std::cout << "Lambda";
        if (!e->params.empty()) {
            std::cout << "(";
            for (size_t i = 0; i < e->params.size(); i++) {
                if (i > 0) std::cout << ", ";
                std::cout << e->params[i];
            }
            std::cout << ")";
        }
        std::cout << "\n";
        for (const auto& s : e->body)
            printStmt(s.get(), level + 1);
        break;
    }
    case ExprType::ArrayLiteral: {
        auto* e = static_cast<const ArrayLiteralExpr*>(expr);
        printIndent(level); std::cout << "ArrayLiteral\n";
        for (const auto& elem : e->elements)
            printExpr(elem.get(), level + 1);
        break;
    }
    case ExprType::Index: {
        auto* e = static_cast<const IndexExpr*>(expr);
        printIndent(level); std::cout << "Index\n";
        printExpr(e->object.get(), level + 1);
        printExpr(e->index.get(), level + 1);
        break;
    }
    case ExprType::IndexAssign: {
        auto* e = static_cast<const IndexAssignExpr*>(expr);
        printIndent(level); std::cout << "IndexAssign\n";
        printExpr(e->object.get(), level + 1);
        printExpr(e->index.get(), level + 1);
        printExpr(e->value.get(), level + 1);
        break;
    }
    case ExprType::MapLiteral: {
        auto* e = static_cast<const MapLiteralExpr*>(expr);
        printIndent(level); std::cout << "MapLiteral\n";
        for (size_t i = 0; i < e->keys.size(); i++) {
            printIndent(level + 1); std::cout << "key:\n";
            if (e->keys[i]) printExpr(e->keys[i].get(), level + 2);
            else { printIndent(level + 2); std::cout << "<spread>\n"; }
            printIndent(level + 1); std::cout << "value:\n";
            printExpr(e->values[i].get(), level + 2);
        }
        break;
    }
    case ExprType::Dot: {
        auto* e = static_cast<const DotExpr*>(expr);
        printIndent(level); std::cout << "Dot(." << e->field << ")\n";
        printExpr(e->object.get(), level + 1);
        break;
    }
    case ExprType::DotAssign: {
        auto* e = static_cast<const DotAssignExpr*>(expr);
        printIndent(level); std::cout << "DotAssign(." << e->field << ")\n";
        printExpr(e->object.get(), level + 1);
        printExpr(e->value.get(), level + 1);
        break;
    }
    case ExprType::Spread: {
        auto* e = static_cast<const SpreadExpr*>(expr);
        printIndent(level); std::cout << "Spread\n";
        printExpr(e->expr.get(), level + 1);
        break;
    }
    case ExprType::Yield: {
        auto* e = static_cast<const YieldExpr*>(expr);
        printIndent(level); std::cout << "Yield\n";
        if (e->value) printExpr(e->value.get(), level + 1);
        break;
    }
    default:
        printIndent(level); std::cout << "Unknown\n";
        break;
    }
}

static void printStmt(const Stmt* stmt, int level) {
    if (!stmt) { printIndent(level); std::cout << "<null>\n"; return; }

    switch (stmt->type) {
    case StmtType::Expr: {
        auto* s = static_cast<const ExprStmt*>(stmt);
        printIndent(level); std::cout << "ExprStmt\n";
        printExpr(s->expr.get(), level + 1);
        break;
    }
    case StmtType::Let: {
        auto* s = static_cast<const LetStmt*>(stmt);
        printIndent(level); std::cout << "Let(" << s->name << ")\n";
        if (s->initializer) printExpr(s->initializer.get(), level + 1);
        break;
    }
    case StmtType::Block: {
        auto* s = static_cast<const BlockStmt*>(stmt);
        printIndent(level); std::cout << "Block\n";
        for (const auto& child : s->statements)
            printStmt(child.get(), level + 1);
        break;
    }
    case StmtType::If: {
        auto* s = static_cast<const IfStmt*>(stmt);
        printIndent(level); std::cout << "If\n";
        printIndent(level + 1); std::cout << "cond:\n";
        printExpr(s->condition.get(), level + 2);
        printIndent(level + 1); std::cout << "then:\n";
        printStmt(s->thenBranch.get(), level + 2);
        for (const auto& elif : s->elifBranches) {
            printIndent(level + 1); std::cout << "elif:\n";
            printExpr(elif.condition.get(), level + 2);
            printStmt(elif.body.get(), level + 2);
        }
        if (s->elseBranch) {
            printIndent(level + 1); std::cout << "else:\n";
            printStmt(s->elseBranch.get(), level + 2);
        }
        break;
    }
    case StmtType::Match: {
        auto* s = static_cast<const MatchStmt*>(stmt);
        printIndent(level); std::cout << "Match\n";
        printExpr(s->subject.get(), level + 1);
        break;
    }
    case StmtType::While: {
        auto* s = static_cast<const WhileStmt*>(stmt);
        printIndent(level); std::cout << "While\n";
        printIndent(level + 1); std::cout << "cond:\n";
        printExpr(s->condition.get(), level + 2);
        printIndent(level + 1); std::cout << "body:\n";
        printStmt(s->body.get(), level + 2);
        break;
    }
    case StmtType::For: {
        auto* s = static_cast<const ForStmt*>(stmt);
        printIndent(level); std::cout << "For(" << s->varName << ")\n";
        printIndent(level + 1); std::cout << "from:\n";
        printExpr(s->start.get(), level + 2);
        printIndent(level + 1); std::cout << "to:\n";
        printExpr(s->end.get(), level + 2);
        printIndent(level + 1); std::cout << "body:\n";
        printStmt(s->body.get(), level + 2);
        break;
    }
    case StmtType::ForIn: {
        auto* s = static_cast<const ForInStmt*>(stmt);
        printIndent(level); std::cout << "ForIn(" << s->varName << ")\n";
        printIndent(level + 1); std::cout << "iterable:\n";
        printExpr(s->iterable.get(), level + 2);
        printIndent(level + 1); std::cout << "body:\n";
        printStmt(s->body.get(), level + 2);
        break;
    }
    case StmtType::Func: {
        auto* s = static_cast<const FuncStmt*>(stmt);
        printIndent(level); std::cout << "Func(" << s->name << ")";
        if (!s->params.empty()) {
            std::cout << " params:";
            for (const auto& p : s->params) std::cout << " " << p;
        }
        std::cout << "\n";
        printStmt(s->body.get(), level + 1);
        break;
    }
    case StmtType::Enum: {
        auto* s = static_cast<const EnumStmt*>(stmt);
        printIndent(level); std::cout << "Enum(" << s->name << ")\n";
        break;
    }
    case StmtType::Class: {
        auto* s = static_cast<const ClassStmt*>(stmt);
        printIndent(level); std::cout << "Class(" << s->name << ")";
        if (!s->superclass.empty()) std::cout << " extends " << s->superclass;
        std::cout << "\n";
        for (const auto& m : s->methods) {
            printIndent(level + 1); std::cout << "Method(" << m.name << ")";
            if (!m.params.empty()) {
                std::cout << " params:";
                for (const auto& p : m.params) std::cout << " " << p;
            }
            std::cout << "\n";
        }
        break;
    }
    case StmtType::Return: {
        auto* s = static_cast<const ReturnStmt*>(stmt);
        printIndent(level); std::cout << "Return\n";
        if (s->value) printExpr(s->value.get(), level + 1);
        break;
    }
    case StmtType::Break:
        printIndent(level); std::cout << "Break\n";
        break;
    case StmtType::Continue:
        printIndent(level); std::cout << "Continue\n";
        break;
    case StmtType::Throw: {
        auto* s = static_cast<const ThrowStmt*>(stmt);
        printIndent(level); std::cout << "Throw\n";
        printExpr(s->value.get(), level + 1);
        break;
    }
    case StmtType::TryCatch: {
        auto* s = static_cast<const TryCatchStmt*>(stmt);
        printIndent(level); std::cout << "TryCatch(" << s->errorVar << ")\n";
        printIndent(level + 1); std::cout << "try:\n";
        printStmt(s->tryBody.get(), level + 2);
        printIndent(level + 1); std::cout << "catch:\n";
        printStmt(s->catchBody.get(), level + 2);
        break;
    }
    case StmtType::Ensure: {
        auto* s = static_cast<const EnsureStmt*>(stmt);
        printIndent(level); std::cout << "Ensure\n";
        printIndent(level + 1); std::cout << "cond:\n";
        printExpr(s->condition.get(), level + 2);
        printIndent(level + 1); std::cout << "else:\n";
        printStmt(s->elseBody.get(), level + 2);
        break;
    }
    case StmtType::Use: {
        auto* s = static_cast<const UseStmt*>(stmt);
        printIndent(level); std::cout << "Use(\"" << s->path << "\") as " << s->alias << "\n";
        break;
    }
    case StmtType::Export: {
        auto* s = static_cast<const ExportStmt*>(stmt);
        printIndent(level); std::cout << "Export {";
        for (size_t i = 0; i < s->names.size(); i++) {
            if (i > 0) std::cout << ", ";
            std::cout << s->names[i];
        }
        std::cout << "}\n";
        break;
    }
    default:
        printIndent(level); std::cout << "Unknown\n";
        break;
    }
}

static void printAst(const std::vector<StmtPtr>& program) {
    for (const auto& stmt : program)
        printStmt(stmt.get(), 0);
}

// ── Main ─────────────────────────────────────────────────────

static std::string readFile(const std::string& path) {
    std::ifstream file(path);
    if (!file.is_open()) {
        std::cerr << "Error: Could not open file '" << path << "'" << std::endl;
        exit(ExitCode::UsageError);
    }
    std::stringstream ss;
    ss << file.rdbuf();
    return ss.str();
}

// Lex + parse source into an AST. Returns empty vector on error or
// when --tokens/--ast consumed the output. Sets hadError on failures.
static std::vector<StmtPtr> compile(const std::string& source,
                                     bool showTokens, bool showAst,
                                     bool& hadError) {
    hadError = false;

    Lexer lexer(source);
    auto tokens = lexer.tokenize();

    if (showTokens) {
        for (const auto& token : tokens)
            std::cout << token << std::endl;
        hadError = lexer.hasError();
        return {};
    }

    if (lexer.hasError()) { hadError = true; return {}; }

    Parser parser(tokens);
    auto program = parser.parse();

    if (parser.hasError()) { hadError = true; return {}; }

    if (showAst) {
        printAst(program);
        return {};
    }

    return program;
}

// readline wrapper — returns empty optional on EOF
static std::optional<std::string> readLine(const char* prompt) {
#ifdef HAVE_READLINE
    char* input = readline(prompt);
    if (!input) return std::nullopt;
    std::string result(input);
    free(input);
    return result;
#else
    std::cout << prompt << std::flush;
    std::string line;
    if (!std::getline(std::cin, line)) return std::nullopt;
    return line;
#endif
}

static void addHistory([[maybe_unused]] const std::string& line) {
#ifdef HAVE_READLINE
    add_history(line.c_str());
#endif
}

static void repl(bool showTokens, bool showAst) {
    std::cout << "Praia " << PRAIA_VERSION << " REPL (type 'exit' to quit)" << std::endl;
    Interpreter interpreter;

    // Keep all ASTs alive so function bodies (raw pointers) remain valid
    std::vector<std::vector<StmtPtr>> astStore;

    for (;;) {
        auto input = readLine(">> ");
        if (!input) break;              // Ctrl-D
        std::string line = *input;
        if (line == "exit") break;
        if (line.empty()) continue;

        // Multi-line: keep reading while braces are unbalanced.
        // Tracks braces correctly by skipping strings and comments.
        auto countBraces = [](const std::string& s) -> int {
            int depth = 0;
            char stringQuote = 0;  // tracks which quote opened the string
            bool inLineComment = false;
            bool inBlockComment = false;
            for (size_t i = 0; i < s.size(); i++) {
                char c = s[i];
                char next = (i + 1 < s.size()) ? s[i + 1] : '\0';

                if (inLineComment) {
                    if (c == '\n') inLineComment = false;
                    continue;
                }
                if (inBlockComment) {
                    if (c == '*' && next == '/') { inBlockComment = false; i++; }
                    continue;
                }
                if (stringQuote) {
                    if (c == '\\') { i++; continue; } // skip escaped char
                    if (c == stringQuote) stringQuote = 0;
                    continue;
                }

                if (c == '/' && next == '/') { inLineComment = true; i++; continue; }
                if (c == '/' && next == '*') { inBlockComment = true; i++; continue; }
                if (c == '"' || c == '\'') { stringQuote = c; continue; }
                if (c == '{') depth++;
                if (c == '}') depth--;
            }
            return depth;
        };

        int braces = countBraces(line);
        while (braces > 0) {
            auto cont = readLine(".. ");
            if (!cont) break;
            line += "\n" + *cont;
            braces = countBraces(line);
        }

        addHistory(line);

        bool hadError = false;
        auto program = compile(line, showTokens, showAst, hadError);
        if (!program.empty()) {
            interpreter.interpretRepl(program);
            astStore.push_back(std::move(program));
        }
    }
}

static void vmRepl(bool showTokens, bool showAst) {
    std::cout << "Praia " << PRAIA_VERSION << " REPL (type 'exit' to quit)" << std::endl;

    extern void vmRegisterNatives(VM& vm);
    VM vm;
    vmRegisterNatives(vm);

    std::vector<std::vector<StmtPtr>> astStore;

    auto countBraces = [](const std::string& s) -> int {
        int depth = 0;
        char stringQuote = 0;
        bool inLineComment = false, inBlockComment = false;
        for (size_t i = 0; i < s.size(); i++) {
            char c = s[i], next = (i + 1 < s.size()) ? s[i + 1] : '\0';
            if (inLineComment) { if (c == '\n') inLineComment = false; continue; }
            if (inBlockComment) { if (c == '*' && next == '/') { inBlockComment = false; i++; } continue; }
            if (stringQuote) { if (c == '\\') { i++; continue; } if (c == stringQuote) stringQuote = 0; continue; }
            if (c == '/' && next == '/') { inLineComment = true; i++; continue; }
            if (c == '/' && next == '*') { inBlockComment = true; i++; continue; }
            if (c == '"' || c == '\'') { stringQuote = c; continue; }
            if (c == '{') depth++;
            if (c == '}') depth--;
        }
        return depth;
    };

    for (;;) {
        auto input = readLine(">> ");
        if (!input) break;
        std::string line = *input;
        if (line == "exit") break;
        if (line.empty()) continue;

        int braces = countBraces(line);
        while (braces > 0) {
            auto cont = readLine(".. ");
            if (!cont) break;
            line += "\n" + *cont;
            braces = countBraces(line);
        }

        addHistory(line);

        bool hadError = false;
        auto program = compile(line, showTokens, showAst, hadError);
        if (program.empty()) continue;

        // Check if the last statement is a bare expression. The
        // earlier `static_cast<const ExprStmt*>(...) != nullptr` was
        // a no-op: static_cast doesn't validate the runtime type on
        // a base→derived downcast, so the result was always non-null
        // for any non-null statement and every REPL line ran through
        // the expression-printing path.
        bool lastIsExpr = program.back()->type == StmtType::Expr;

        Compiler compiler;
        auto script = compiler.compile(program);
        if (!script) continue;

        // If the last statement is an expression, patch the bytecode:
        // The compiler emits: <expr> OP_POP ... OP_NIL OP_RETURN
        // We remove the OP_POP and OP_NIL so the expression value
        // flows directly into OP_RETURN as the script's result.
        if (lastIsExpr) {
            auto& code = script->chunk.code;
            // The epilogue is always the last 2 bytes: OP_NIL OP_RETURN
            // Before that, the ExprStmt's OP_POP is the byte just before OP_NIL
            int sz = static_cast<int>(code.size());
            if (sz >= 3 &&
                code[sz - 1] == static_cast<uint8_t>(OpCode::OP_RETURN) &&
                code[sz - 2] == static_cast<uint8_t>(OpCode::OP_NIL) &&
                code[sz - 3] == static_cast<uint8_t>(OpCode::OP_POP)) {
                // Remove OP_POP and OP_NIL, keep OP_RETURN
                code.erase(code.begin() + (sz - 3), code.begin() + (sz - 1));
            }
        }

        try {
            auto result = vm.runRepl(script);
            if (result == VM::Result::OK && lastIsExpr) {
                Value val = vm.pop();
                if (!val.isNil())
                    std::cout << val.toString() << "\n";
            }
        } catch (const ExitSignal&) {
            throw;
        }

        astStore.push_back(std::move(program));
    }
}

/* Per-file isolation via subprocess: every test file runs in its own
   `praia [--tree] --test-file <path>` invocation. The child inherits
   no state from prior files (fds, async threads, retained futures all
   die with it), which eliminated the long-tail flake caused by the
   HTTP test files' `while (true) { accept }` server loops piling up
   across an in-process run.

   The runner can also fan multiple subprocesses out concurrently via
   `-j N`. To keep output readable under parallelism, each child's
   stdout+stderr is redirected to its own anonymous temp file
   (`mkstemp` + `unlink`); the parent reads it back after `waitpid`
   and prints it as one block under that file's header. Sequential
   (`-j 1`, the default) uses the exact same plumbing, just one job
   at a time, so behaviour is identical to the previous in-process
   runner with one exception:

     - A test file that returns from `main` without calling
       `testing.done()` / `sys.exit` is treated as failed via the
       `--test-file` flag (the child's script path notices the flag
       and exits with code 2 + a stderr line).

   Exit-code mapping per child:
     - WIFEXITED  → WEXITSTATUS (preserves user-chosen sys.exit code).
     - WIFSIGNALED → 128 + signal, with a clear `(crashed by signal
       N (NAME))` stderr line attached to the offending file.
     - fork/exec/mkstemp failure → runner-level abort. The failure is
       not charged to any individual test file (it's an infrastructure
       fault, not the file's). The runner stops enqueueing new spawns,
       drains already-running children, and returns ExitCode::RuntimeError
       once everything has finished.
*/
struct PendingTest {
    pid_t pid = -1;
    int   outFd = -1;
    // Parent's read end of the pre-exec error channel. The child holds
    // the (CLOEXEC) write end open until execv: on successful exec the
    // kernel auto-closes it (parent's read returns 0); on any failure
    // before exec the child writes a marker byte first, so the parent
    // can distinguish "child died before running the script" (runner
    // infrastructure fault → ExitCode::RuntimeError) from "script ran
    // and exited with code 127" (a real test failure).
    int   errFd = -1;
    std::string file;
};

static PendingTest spawnTestFile(const std::string& path, bool useVm) {
    namespace fs = std::filesystem;
    PendingTest pt;
    pt.file = path;

    // Anonymous capture file: mkstemp + immediate unlink. The fd lives
    // until we close it; on close the kernel reclaims the inode.
    // fs::temp_directory_path() honors $TMPDIR / $TMP / $TEMP /
    // $TEMPDIR on POSIX and falls back to /tmp — works on locked-down
    // hosts where /tmp itself isn't writable (sandboxes, containers).
    std::error_code tmpEc;
    fs::path tmpDir = fs::temp_directory_path(tmpEc);
    if (tmpEc) {
        const char* env = std::getenv("TMPDIR");
        tmpDir = env ? env : "/tmp";
    }
    std::string tmplStr = (tmpDir / "praia-test-out.XXXXXX").string();
    std::vector<char> tmpl(tmplStr.begin(), tmplStr.end());
    tmpl.push_back('\0');
    pt.outFd = mkstemp(tmpl.data());
    if (pt.outFd < 0) {
        std::cerr << "praia test: mkstemp(" << tmplStr << ") failed: "
                  << std::strerror(errno) << std::endl;
        return pt;
    }
    unlink(tmpl.data());

    // Mark close-on-exec so concurrent siblings (parallel `-j N`)
    // don't inherit this fd through fork+exec. The child that owns
    // *this* outFd `dup2`s it onto STDOUT/STDERR (which lose CLOEXEC)
    // and explicitly closes it before exec, so the redirection still
    // works; only the inherited copies in siblings get auto-closed.
    int flags = fcntl(pt.outFd, F_GETFD);
    if (flags < 0 || fcntl(pt.outFd, F_SETFD, flags | FD_CLOEXEC) < 0) {
        std::cerr << "praia test: fcntl(FD_CLOEXEC) failed: "
                  << std::strerror(errno) << std::endl;
        close(pt.outFd);
        pt.outFd = -1;
        return pt;
    }

    // Pre-exec error pipe. Both ends are CLOEXEC: parent's read end so
    // sibling exec'd children don't inherit it (would hold the write
    // side open and stall the read); write end so a successful exec
    // auto-closes it (parent's read returns 0, "exec succeeded").
    int errPipe[2];
    if (pipe(errPipe) < 0) {
        std::cerr << "praia test: pipe failed: " << std::strerror(errno) << std::endl;
        close(pt.outFd); pt.outFd = -1;
        return pt;
    }
    for (int fd : {errPipe[0], errPipe[1]}) {
        int f = fcntl(fd, F_GETFD);
        if (f < 0 || fcntl(fd, F_SETFD, f | FD_CLOEXEC) < 0) {
            std::cerr << "praia test: fcntl(FD_CLOEXEC) on pipe failed: "
                      << std::strerror(errno) << std::endl;
            close(errPipe[0]); close(errPipe[1]);
            close(pt.outFd); pt.outFd = -1;
            return pt;
        }
    }

    pt.pid = fork();
    if (pt.pid < 0) {
        std::cerr << "praia test: fork failed: " << std::strerror(errno) << std::endl;
        close(errPipe[0]); close(errPipe[1]);
        close(pt.outFd); pt.outFd = -1;
        return pt;
    }
    if (pt.pid == 0) {
        // Child stays in the parent's process group so terminal SIGINT
        // (Ctrl-C) reaches it via the foreground-group dispatch.
        close(errPipe[0]);
        int errWrite = errPipe[1];
        auto preExecFail = [&](const char* what) {
            // Diagnose to the inherited stderr (or to the captured
            // temp file if stderr was already dup2'd). The marker byte
            // is what the parent reads — its contents don't matter,
            // only that the read returns > 0 bytes.
            std::fprintf(stderr, "praia test: %s failed: %s\n",
                         what, std::strerror(errno));
            char marker = 1;
            ssize_t w = write(errWrite, &marker, 1);
            (void)w; // best-effort; parent treats any non-empty read as failure
            _exit(127);
        };
        if (dup2(pt.outFd, STDOUT_FILENO) < 0) preExecFail("dup2(stdout)");
        if (dup2(pt.outFd, STDERR_FILENO) < 0) preExecFail("dup2(stderr)");
        close(pt.outFd);
        std::vector<char*> argv;
        argv.push_back(const_cast<char*>(g_praiaExecPath.c_str()));
        if (!useVm) argv.push_back(const_cast<char*>("--tree"));
        argv.push_back(const_cast<char*>("--test-file"));
        argv.push_back(const_cast<char*>(path.c_str()));
        argv.push_back(nullptr);
        execv(g_praiaExecPath.c_str(), argv.data());
        preExecFail("exec");
    }
    close(errPipe[1]);
    pt.errFd = errPipe[0];
    return pt;
}

static int runTestsCommand(const std::string& dir, bool useVm, int jobs) {
    namespace fs = std::filesystem;
    if (g_praiaExecPath.empty()) {
        std::cerr << "praia test: could not locate own executable for "
                  << "subprocess test runner" << std::endl;
        return ExitCode::RuntimeError;
    }
    if (!fs::exists(dir)) {
        std::cerr << "praia test: directory not found: " << dir << std::endl;
        return ExitCode::UsageError;
    }
    if (!fs::is_directory(dir)) {
        std::cerr << "praia test: not a directory: " << dir << std::endl;
        return ExitCode::UsageError;
    }
    if (jobs < 1) jobs = 1;

    std::vector<std::string> files;
    // Don't recurse into directory symlinks (loop risk), but file symlinks
    // are fine — match the default behavior of Go/Rust/Java/Python/find.
    // skip_permission_denied prevents throws on unreadable subtrees.
    fs::recursive_directory_iterator it(
        dir, fs::directory_options::skip_permission_denied);
    fs::recursive_directory_iterator end;
    for (; it != end; ++it) {
        const auto& entry = *it;
        bool isFile;
        if (entry.is_symlink()) {
            std::error_code ec;
            auto st = fs::status(entry.path(), ec);
            if (ec || !fs::exists(st)) continue;       // broken: skip
            if (fs::is_directory(st)) {
                it.disable_recursion_pending();          // don't follow
                continue;
            }
            isFile = fs::is_regular_file(st);
        } else {
            isFile = entry.is_regular_file();
        }
        if (!isFile) continue;
        const auto& p = entry.path();
        if (p.extension() == ".praia" &&
            p.filename().string().starts_with("test_")) {
            files.push_back(p.string());
        }
    }
    std::sort(files.begin(), files.end());

    if (files.empty()) {
        std::cerr << "praia test: no test_*.praia files in " << dir << std::endl;
        return ExitCode::UsageError;
    }

    int passed = 0, failed = 0;
    int total = static_cast<int>(files.size());
    int completed = 0;
    std::vector<std::string> failedFiles;
    std::vector<PendingTest> running;
    size_t nextToSpawn = 0;

    auto printHeaderAndOutput = [&](const std::string& file,
                                    const std::string& output,
                                    const std::string& crashLine) {
        // Progress: [####....] N/total filename, where N counts this
        // just-finished file. `completed` is incremented by the
        // callers after this lambda returns; we use `completed + 1`
        // here so the bar reaches `total/total` on the last file.
        int done = completed + 1;
        int barWidth = 20;
        int filled = (done * barWidth) / std::max(total, 1);
        std::string bar(filled, '#');
        bar += std::string(barWidth - filled, '.');
        std::string fname = file;
        auto slash = fname.rfind('/');
        if (slash != std::string::npos) fname = fname.substr(slash + 1);
        std::cout << "\r\033[K[" << bar << "] " << done << "/" << total
                  << " " << fname << std::flush;
        std::cout << "\r\033[K── " << file << " ───────────────────────" << std::endl;
        std::cout << output;
        if (!crashLine.empty()) std::cerr << crashLine << std::endl;
        std::cout << std::endl;
    };

    // Runner-level failure (mkstemp / fork blew up — process-wide
    // resource exhaustion, not a fault of the test file). When set we
    // stop enqueueing new spawns, let already-running children drain
    // to completion, then return ExitCode::RuntimeError. The flag is
    // distinct from per-file pass/fail so we don't mis-attribute the
    // failure to whichever file happened to be next in line.
    bool runnerError = false;

    while (nextToSpawn < files.size() || !running.empty()) {
        // Spawn until we hit the job cap (or run out of files), unless
        // a runner-level error has occurred — then stop enqueueing
        // and let pending children drain.
        if (!runnerError) {
            while (nextToSpawn < files.size() && (int)running.size() < jobs) {
                auto pt = spawnTestFile(files[nextToSpawn], useVm);
                if (pt.pid < 0) {
                    runnerError = true;
                    break;
                }
                running.push_back(std::move(pt));
                nextToSpawn++;
            }
        }
        // Nothing running + nothing more to enqueue → we're done.
        if (running.empty()) break;

        // Wait for any child to finish.
        int status = 0;
        pid_t done = waitpid(-1, &status, 0);
        if (done < 0) {
            if (errno == EINTR) continue;
            std::cerr << "praia test: waitpid failed: " << std::strerror(errno) << std::endl;
            return ExitCode::RuntimeError;
        }
        auto job = std::find_if(running.begin(), running.end(),
            [&](const PendingTest& j) { return j.pid == done; });
        if (job == running.end()) continue; // not one of ours

        // Drain captured output from the child's temp file.
        std::string output;
        if (job->outFd >= 0) {
            lseek(job->outFd, 0, SEEK_SET);
            char buf[4096];
            ssize_t n;
            while ((n = read(job->outFd, buf, sizeof(buf))) > 0)
                output.append(buf, static_cast<size_t>(n));
            close(job->outFd);
        }

        // Drain the pre-exec error channel. Any bytes here mean the
        // child died before execv() (dup2 failure, exec failure, etc.)
        // — that's runner infrastructure, not the test file's fault.
        // A successful exec closes the write end via CLOEXEC, so the
        // read returns 0 and we fall through to the normal path.
        bool preExecFailed = false;
        if (job->errFd >= 0) {
            char ebuf[16];
            ssize_t n = read(job->errFd, ebuf, sizeof(ebuf));
            if (n > 0) preExecFailed = true;
            close(job->errFd);
        }

        // Map waitpid status to exit code + optional crash diagnostic.
        int code;
        std::string crashLine;
        if (WIFEXITED(status)) {
            code = WEXITSTATUS(status);
        } else if (WIFSIGNALED(status)) {
            int sig = WTERMSIG(status);
            const char* desc = strsignal(sig);
            if (!desc) desc = "unknown signal";
            crashLine = "  (crashed by signal " + std::to_string(sig)
                      + " (" + desc + "))";
            code = 128 + sig;
        } else {
            code = 1;
        }

        printHeaderAndOutput(job->file, output, crashLine);

        if (preExecFailed) {
            // Don't attribute to job->file — the script never ran.
            // Flip runnerError so the main loop stops enqueueing and
            // the footer prints the abort message + RuntimeError.
            runnerError = true;
        } else if (code == 0) {
            passed++;
        } else {
            failed++; failedFiles.push_back(job->file);
        }
        completed++;
        running.erase(job);
    }

    // Final progress bar + summary. When the runner aborted early
    // (mkstemp/fork failure), draw the bar to actual completion and
    // tag it "(aborted)" so the user doesn't see a full bar over an
    // incomplete run.
    {
        int barWidth = 20;
        int filled = (completed * barWidth) / std::max(total, 1);
        std::string bar(filled, '#');
        bar += std::string(barWidth - filled, '.');
        std::cout << "\r\033[K[" << bar << "] " << completed << "/" << total
                  << (runnerError ? " (aborted)" : " done") << std::endl;
    }
    std::cout << "═══ " << passed << "/" << files.size()
              << " test files passed ═══" << std::endl;
    if (!failedFiles.empty()) {
        // Stable order: failed files were collected in finish-order
        // (which is spawn-order under -j 1 but arbitrary under -j N).
        // Sort alphabetically so CI output is deterministic.
        std::sort(failedFiles.begin(), failedFiles.end());
        std::cout << "Failed:" << std::endl;
        for (auto& f : failedFiles) std::cout << "  " << f << std::endl;
    }
    // Runner-level error (spawn failure) takes precedence over the
    // pass/fail tally: even if every test that *did* run passed, we
    // exited early without running the remainder, so the suite result
    // is incomplete. Return RuntimeError rather than 0.
    if (runnerError) {
        std::cerr << "praia test: aborted — could not spawn subprocess for "
                  << "remaining test files (see earlier error)" << std::endl;
        return ExitCode::RuntimeError;
    }
    return failed == 0 ? 0 : 1;
}

int main(int argc, char* argv[]) {
    // Force line buffering on stdout/stderr. By default C++ block-buffers
    // stdout when it isn't a TTY (e.g. piped to a file or grep), which
    // delays log output until the script exits. Servers and long-running
    // scripts want their `print` and logger output to appear in real time.
    setvbuf(stdout, nullptr, _IOLBF, 0);
    setvbuf(stderr, nullptr, _IONBF, 0);

    // Ignore SIGPIPE process-wide. Without this, an HTTP client that
    // disconnects mid-response makes the next send() raise SIGPIPE, which
    // by default kills the server. With SIG_IGN, send() returns -1 with
    // EPIPE instead and the calling code can handle it gracefully.
    signal(SIGPIPE, SIG_IGN);

    installDefaultSignalHandlers();

    // Resolve the directory where the praia binary lives AND the full
    // canonical path to the binary itself. The directory is used by
    // grain resolution to find bundled stdlib grains; the full path is
    // used by `praia test` to fork+exec ourselves per test file for
    // subprocess isolation.
    {
        namespace fs = std::filesystem;
        fs::path arg0(argv[0]);
        fs::path resolved;
        if (arg0.is_absolute() || arg0.string().find('/') != std::string::npos) {
            // Absolute or relative path — resolve directly
            try { resolved = fs::canonical(arg0); }
            catch (...) {}
        } else {
            // Bare name (e.g. "praia") — search PATH. Skip directory
            // entries: a same-named directory passes access(X_OK) (the
            // "traverse" bit for dirs) but execv on it later fails
            // with EISDIR. Then require execute permission, not just
            // file existence, so a non-executable file at the matching
            // path doesn't short-circuit the search either.
            const char* pathEnv = std::getenv("PATH");
            if (pathEnv) {
                std::istringstream paths(pathEnv);
                std::string dir;
                while (std::getline(paths, dir, ':')) {
                    auto candidate = fs::path(dir) / arg0;
                    std::error_code ec;
                    if (fs::is_directory(candidate, ec) || ec) continue;
                    if (access(candidate.c_str(), X_OK) != 0) continue;
                    try { resolved = fs::canonical(candidate); } catch (...) {}
                    if (!resolved.empty()) break;
                }
            }
        }
        if (!resolved.empty()) {
            g_praiaExecPath   = resolved.string();
            g_praiaInstallDir = resolved.parent_path().string();
        }
    }

    bool showTokens = false;
    bool showAst = false;
    bool useVm = true; // VM is the default
    std::string filename;
    int fileArgIndex = -1;

    // `praia -v` / `praia --version`
    if (argc >= 2 && (std::string(argv[1]) == "--version" || std::string(argv[1]) == "-v")) {
        std::cout << "Praia Version " << PRAIA_VERSION << std::endl;
        return ExitCode::Success;
    }

    // `praia --include-path` — print the header directory for native plugins
    if (argc >= 2 && std::string(argv[1]) == "--include-path") {
#ifdef PRAIA_LIBDIR
        std::cout << PRAIA_LIBDIR << "/include" << std::endl;
#else
        // Development mode: headers are in src/ relative to the binary
        std::cout << fs::canonical(fs::path(argv[0]).parent_path() / "src").string() << std::endl;
#endif
        return ExitCode::Success;
    }

    // `praia -h` / `praia --help`
    if (argc >= 2 && (std::string(argv[1]) == "--help" || std::string(argv[1]) == "-h")) {
        std::cout << "Praia " << PRAIA_VERSION << "\n\n"
                  << "Usage:\n"
                  << "  praia                          Start the REPL\n"
                  << "  praia <file>                   Run a script\n"
                  << "  praia <file> [args...]          Run a script with arguments (sys.args)\n"
                  << "  praia -c '<code>' [args...]     Run a one-liner\n"
                  << "  praia test [-j N] [dir]         Run test suite (default: tests/)\n"
                  << "\n"
                  << "Options:\n"
                  << "  -h, --help       Show this help message\n"
                  << "  -v, --version    Print version\n"
                  << "  -c <code>        Evaluate a string as code\n"
                  << "  -j N             (test) Run up to N test files in parallel (default 1)\n"
                  << "  --tree           Use tree-walker interpreter instead of VM\n"
                  << "  --tokens         Print lexer tokens and exit\n"
                  << "  --ast            Print parse tree and exit\n"
                  << "  --include-path   Print the header path for native plugins\n"
                  << "\n"
                  << "Exit codes:\n"
                  << "  0  success\n"
                  << "  1  usage error (bad args, file not found)\n"
                  << "  2  compile error (syntax / parse)\n"
                  << "  3  runtime error\n"
                  << "  N  sys.exit(N) — user-defined\n";
        return ExitCode::Success;
    }

    // `praia test [dir]` subcommand — scan past flags to find it
    for (int i = 1; i < argc; i++) {
        std::string arg = argv[i];
        if (arg == "--tree") useVm = false;
        else if (arg == "--vm") useVm = true;
        else if (arg == "test") {
            // Scan remaining args for flags and an optional directory.
            // `-j N` opts into parallel subprocess execution; default
            // is 1 (sequential), keeping the deterministic-order
            // contract for `praia test` invocations without the flag.
            std::string dir = "tests";
            bool dirSet = false;
            int jobs = 1;
            for (int j = i + 1; j < argc; j++) {
                std::string a = argv[j];
                if (a == "--tree") useVm = false;
                else if (a == "--vm") useVm = true;
                else if (a == "-j") {
                    if (j + 1 >= argc) {
                        std::cerr << "praia test: -j requires an integer (e.g. -j 4)\n";
                        return ExitCode::UsageError;
                    }
                    // Use stoi's pos out-param + size check so trailing
                    // garbage like "-j 4abc" is rejected (plain stoi
                    // would silently parse 4 and drop the rest).
                    std::string jobsArg = argv[++j];
                    try {
                        size_t pos = 0;
                        jobs = std::stoi(jobsArg, &pos);
                        if (pos != jobsArg.size()) throw std::invalid_argument("trailing");
                    } catch (...) {
                        std::cerr << "praia test: -j needs a positive integer\n";
                        return ExitCode::UsageError;
                    }
                    if (jobs < 1) {
                        std::cerr << "praia test: -j must be >= 1\n";
                        return ExitCode::UsageError;
                    }
                }
                else if (!a.empty() && a[0] != '-') {
                    // Positional argument: the test directory. Only
                    // one is allowed; reject extras instead of
                    // silently using the first and ignoring the rest.
                    if (dirSet) {
                        std::cerr << "praia test: unexpected argument: " << a
                                  << " (test dir already set to '" << dir << "')"
                                  << std::endl;
                        return ExitCode::UsageError;
                    }
                    dir = a;
                    dirSet = true;
                }
                else {
                    // Anything else starting with '-' is an unknown flag
                    // (e.g. "-j4" with no space, "--foo", a typo'd
                    // option). Reject loudly rather than silently
                    // skipping — silent skip turned typos into
                    // unexplained "default behavior" runs. Previously
                    // we broke out of this loop on the first positional
                    // arg, so `praia test tests --bad-flag` slipped
                    // past this check; continuing the scan after dir
                    // is set closes that hole.
                    std::cerr << "praia test: unknown option: " << a << std::endl;
                    return ExitCode::UsageError;
                }
            }
            return runTestsCommand(dir, useVm, jobs);
        }
        else if (!arg.empty() && arg[0] != '-') break; // hit a non-flag, non-"test" arg (filename)
    }

    // Parse all flags first
    std::string cCode;
    bool hasCFlag = false;
    int cArgStart = -1;
    // Internal flag set by the `praia test` subprocess runner. Tells
    // this child process to treat "the script returned without calling
    // sys.exit" as a failure — preserves the in-process runner's
    // contract that test files must end via testing.done() / sys.exit.
    bool testFileMode = false;

    for (int i = 1; i < argc; i++) {
        std::string arg = argv[i];
        if (arg == "--tokens")        showTokens = true;
        else if (arg == "--ast")      showAst = true;
        else if (arg == "--vm")       useVm = true;
        else if (arg == "--tree")     useVm = false;
        else if (arg == "--test-file") testFileMode = true;
        else if (arg == "-c") {
            if (i + 1 >= argc) {
                std::cerr << "Error: -c requires an argument\n";
                return ExitCode::UsageError;
            }
            hasCFlag = true;
            cCode = argv[++i];
            cArgStart = i + 1;
            break;
        }
        else if (filename.empty()) { filename = arg; fileArgIndex = i; break; }
    }

    // `praia [-vm] -c "code"` — run a one-liner
    if (hasCFlag) {
        bool hadError = false;
        auto program = compile(cCode, showTokens, showAst, hadError);
        if (hadError) return ExitCode::CompileError;
        if (!program.empty()) {
            if (useVm) {
                Compiler compiler;
                auto script = compiler.compile(program);
                if (!script) return ExitCode::CompileError;
                extern void vmRegisterNatives(VM& vm);
                VM vm;
                vmRegisterNatives(vm);
                std::vector<std::string> scriptArgs;
                for (int i = cArgStart; i < argc; i++)
                    scriptArgs.push_back(argv[i]);
                vm.setArgs(scriptArgs);
                try {
                    return vm.run(script) == VM::Result::OK
                        ? ExitCode::Success : ExitCode::RuntimeError;
                }
                catch (const ExitSignal& e) { return e.code; }
            } else {
                Interpreter interpreter;
                std::vector<std::string> scriptArgs;
                for (int i = cArgStart; i < argc; i++)
                    scriptArgs.push_back(argv[i]);
                interpreter.setArgs(scriptArgs);
                try {
                    if (!interpreter.interpret(program)) return ExitCode::RuntimeError;
                }
                catch (const ExitSignal& e) { return e.code; }
            }
        }
        return ExitCode::Success;
    }

    if (filename.empty()) {
        try {
            if (useVm) vmRepl(showTokens, showAst);
            else repl(showTokens, showAst);
        }
        catch (const ExitSignal& e) { return e.code; }
        return ExitCode::Success;
    }

    // Collect script arguments (everything after the filename)
    std::vector<std::string> scriptArgs;
    for (int i = fileArgIndex + 1; i < argc; i++)
        scriptArgs.push_back(argv[i]);

    std::string source = readFile(filename);
    bool hadError = false;
    auto program = compile(source, showTokens, showAst, hadError);
    if (hadError) return ExitCode::CompileError;
    if (!program.empty()) {
        // Helper: when running under `praia test`'s subprocess runner,
        // a clean script return without sys.exit means testing.done()
        // was never called. Surface that loudly so a malformed test
        // file is flagged rather than silently passing.
        auto reportMissingTestingDone = [&]() {
            std::cerr << "praia test: " << filename
                      << " finished without calling testing.done()" << std::endl;
        };
        if (useVm) {
            // Bytecode VM path
            Compiler compiler;
            auto script = compiler.compile(program);
            if (!script) return ExitCode::CompileError;

            extern void vmRegisterNatives(VM& vm);
            VM vm;
            vmRegisterNatives(vm);
            vm.setArgs(scriptArgs);
            vm.setCurrentFile(filename);
            try {
                auto result = vm.run(script);
                if (result != VM::Result::OK) return ExitCode::RuntimeError;
                if (testFileMode) { reportMissingTestingDone(); return 2; }
                return ExitCode::Success;
            } catch (const ExitSignal& e) { return e.code; }
        } else {
            // Tree-walker path
            Interpreter interpreter;
            interpreter.setArgs(scriptArgs);
            interpreter.setCurrentFile(filename);
            try {
                if (!interpreter.interpret(program)) return ExitCode::RuntimeError;
                if (testFileMode) { reportMissingTestingDone(); return 2; }
            }
            catch (const ExitSignal& e) { return e.code; }
        }
    }
    return ExitCode::Success;
}
